name: solar_icons
description: Solar Icons is Solar icons which is 7000+ icons in different styles or 1200+ icons for each style available as a dart/flutter package
version: 0.0.1
repository: https://github.com/CoderNamedHendrick/solar_icons
homepage: https://github.com/CoderNamedHendrick/solar_icons

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  fonts:
    - family: SolarIconsBold
      fonts:
        - asset: fonts/SolarIconsBold.ttf

    - family: SolarIconsBroken
      fonts:
        - asset: fonts/SolarIconsBroken.ttf

    - family: SolarIconsOutline
      fonts:
        - asset: fonts/SolarIconsOutline.ttf