name: solar_icons
description: Solar Icons is Solar icons which is 7000+ icons in different styles or 1200+ icons for each style available as a dart/flutter package
version: 0.2.0
repository: https://github.com/CoderNamedHendrick/solar_icons
homepage: https://github.com/CoderNamedHendrick/solar_icons

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  fonts:
    - family: SolarIcons
      fonts:
        - asset: fonts/SolarIcons.ttf
